### ISSUE TITLE
How can I store an image?

### ISSUE THREAD

**Issue by Mikiewitch** [geeklearningio/gl-dotnet-storage#60]
Hello everyone,
I've tried to save the image by setting the content type to image/png. The file at the disk has the type "file" though.  My call looks like this:
await fileStore.SaveAsync(imageBytes, "/picture", "image/png");

Any advice?

Cheers,
Ondrej

**Comment by sandorfr** [comment]
what do you mean by has the type file?

**Comment by Mikiewitch** [comment]
![glstorage](https://user-images.githubusercontent.com/24904494/30701615-02fa2d1c-9eeb-11e7-8a5b-393ede541c0f.png)

**Comment by sandorfr** [comment]
ah.. you're talking about windows explorer :). that's related to the file extension. Since you did not provide one in your path, windows does not know what it is. Metadata and Properties are emulated on File system by storing them in a `.{0}-extended-properties` subdirectory. 

You can retrieve them later using the [GetAsync api](https://github.com/geeklearningio/gl-dotnet-storage/blob/21bace775cea367fe74259ce63975f9b75792b3e/src/GeekLearning.Storage/IStore.cs#L17-L19)

The server middleware if you are using it will also [set the response content type accordingly](https://github.com/geeklearningio/gl-dotnet-storage/blob/21bace775cea367fe74259ce63975f9b75792b3e/src/GeekLearning.Storage.FileSystem.Server/FileSystemStorageServerMiddleware.cs#L51)

**Comment by Mikiewitch** [comment]
Great, thank you.
